"""
Author: Soumil Ramesh Kulkarni
Date: 05.15.2024

Question:
You are given string s of length n, having m wildcard characters '?', where each wildcard character
represents a single character. Write a program which returns a list of all possible distinct strings
that can be generated by replacing each wildcard character in s with either '0' or '1'.

Any string returned must not contain '?' characters, all must be replaced with either '0' or '1'.

Example One
{
"s": "1?10"
}
Output:

["1010", "1110"]
Example Two
{
"s": "1?0?"
}
Output:

["1000", "1001", "1100", "1101"]
Input string has two '?' characters. Each one can be replaced with either '0' or '1' making the
total number of distinct strings 22 = 4.
"""


def find(s,res):
    if '?' in s:
        s1=s.replace('?','0',1)
        s2=s.replace('?','1',1)
        find(s1,res)
        find(s2,res)
    else:
        res.append(s)
def find_all_possibilities(s):
    res=[]
    find(s,res)
    return res
